# Generated by Django 4.1.7 on 2023-03-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.CharField(choices=[('5', 'Five'), ('4', 'Four'), ('3', 'Three'), ('2', 'Two'), ('1', 'One')], default='1', max_length=100, verbose_name='Оценка'),
        ),
    ]
