# Generated by Django 4.1.7 on 2023-03-25 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0002_alter_review_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.PositiveIntegerField(choices=[('5', 'Отлично'), ('4', 'Хорошо'), ('3', 'Среднее'), ('2', 'Плохо'), ('1', 'Очень Плохо')], default='3', verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback_app.product', verbose_name='Продукты'),
        ),
    ]
