# Generated by Django 4.1.7 on 2023-03-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0003_alter_review_grade_alter_review_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.IntegerField(choices=[('5', 'Отлично'), ('4', 'Хорошо'), ('3', 'Среднее'), ('2', 'Плохо'), ('1', 'Очень Плохо')], default='3', verbose_name='Оценка'),
        ),
    ]
