# Generated by Django 4.1.7 on 2023-03-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0004_alter_review_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Games', 'Игры'), ('Health', 'Здоровье'), ('Sport', 'Спорт'), ('Beauty', 'Красота'), ('Kitchen', 'Кухня'), ('Clothes', 'Одежда'), ('Other', 'Разное')], default='Other', max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.IntegerField(choices=[(5, 'Отлично'), (4, 'Хорошо'), (3, 'Среднее'), (2, 'Плохо'), (1, 'Очень Плохо')], default=3, verbose_name='Оценка'),
        ),
    ]
